### ISSUE TITLE
new_zk_ensemble doesn't start the server

### ISSUE THREAD

**Issue by vkokatnur** [lucidworks/solr-scale-tk#18]
new_zk_ensemble uses paravirtual image : ami-5d126438 which has java 1.8.0_60 installed.  But the fabfile.py script refers to 1.8.0_102.  This stops zookeeper server from booting up.  Here is the log : 

**nohup: failed to run command `/home/ec2-user/jdk1.8.0_102/bin/java': No such file or directory**

A new java_path needs to be added for zookeeper, or image needs to be updated/replaced.

**Comment by gsingers** [comment]
Are you still seeing this @vkokatnur?

**Comment by vkokatnur** [comment]
@gsingers It is now resolved with the new image.
